
INSERT INTO USUARIOS (USERNAME, PASSWORD, VICTORIAS, DERROTAS)
VALUES('SKing','contraseñaSKing', 1, 2);

INSERT INTO USUARIOS (USERNAME, PASSWORD, VICTORIAS, DERROTAS)
VALUES('usuarioRaro','contraseñaRaro', 15, 7);

INSERT INTO USUARIOS (USERNAME, PASSWORD, VICTORIAS, DERROTAS)
VALUES('top','contraseñaTop', 25, 4);

INSERT INTO USUARIOS (USERNAME, PASSWORD, VICTORIAS, DERROTAS)
VALUES('lalala','contraseñalalala', 12, 5);

INSERT INTO USUARIOS (USERNAME, PASSWORD, VICTORIAS, DERROTAS)
VALUES('malo','contraseñamalo', 21, 18);

INSERT INTO USUARIOS (USERNAME, PASSWORD, VICTORIAS, DERROTAS)
VALUES('yo','miPassword', 20, 10);